### ISSUE TITLE
Kötelező attribútumok hiánya végtelen redirect

### ISSUE THREAD

**Issue by szabogyula** [hexaaproject/hexaa-backend#1]
Ha egy felhasználó email cím nélkül érkezik, akkor végtelen redirectbe kerül a rendszer. Kellene egy figyelmeztető oldal, ami figyelmeztet a hiányzó attribútumokra. ("Keresd az IdP üzemeltetőjét...")

**Comment by bkotyik** [comment]
Megjelenítendő név (display name) hiányára a felület fog figyelmeztetni a vezérlőpanelen (dashboard),
az eppn és mail hiánya viszont lehetetlenné teszi az authentikálást, így az az authentikáció után közvetlenül fog hibát jelezni. Ekkor viszont magától értetődően a felület nem fog megjelenni.

Következő update-tel jön.
