### ISSUE TITLE
A "Profile" menüpont rossz helyre visz

### ISSUE THREAD

**Issue by torlasz** [hexaaproject/hexaa-backend#2]
Ha a jobb fölső sarokban az eppn-ből legördülő menüből azt választom, hogy "Profile", akkor nem a profilom jön föl, hanem a news. Ha a bal oldali menüből választom a Me menüpontot, az tényleg a profiloldalra visz.

**Comment by bkotyik** [comment]
Köszönöm szépen a visszajelzést. Ez eddig szándékos volt, de úgy tűnik megtévesztő az elnevezés. A menüpontban a "Profilom" nem konkrétan a profil beállításokra, sokkal inkább a profillal kapcsolatos adatok megjelenítésére vonatkozik. Úgy éreztem, hogy a legjobb összefoglaló képet a profillal kapcsolatban a hírfolyam nyújtja. Átgondolom a dolgot, és igyekszem egyértelműsíteni a dolgot, vagy egy plusz menüponttal a profil beállításokat is kivezetni a menüsori legőrdülő menübe.
